### ISSUE TITLE
`awg[Amplitude]` vs. `awg[Amplitude, ::Integer]` inconsistent

### ISSUE THREAD

**Issue by ajkeller34** [PainterQubits/InstrumentControl.jl#33]
[This method](https://github.com/PainterQubits/InstrumentControl.jl/blob/952a9d3c8d2c3293eeff0f289bc20b6647817ef6/src/instruments/AWGs/M320XA/Inspect.jl#L5) and [this method](https://github.com/PainterQubits/InstrumentControl.jl/blob/952a9d3c8d2c3293eeff0f289bc20b6647817ef6/src/instruments/AWGs/M320XA/Inspect.jl#L17) can give different results:

![image](https://user-images.githubusercontent.com/7145721/35022653-e94eb92a-faeb-11e7-9357-9ec37dff0f17.png)

cc @vtdsferreira

**Comment by vtdsferreira** [comment]
This was by design actually. I wanted a way to see the InstrumentProperty
values of all the channels at once. The idea is, if you don't specify a
channel, you get information for all of them

On Jan 16, 2018 18:36, "Andrew Keller" <notifications@github.com> wrote:

This method
<https://github.com/PainterQubits/InstrumentControl.jl/blob/952a9d3c8d2c3293eeff0f289bc20b6647817ef6/src/instruments/AWGs/M320XA/Inspect.jl#L5>
and this method
<https://github.com/PainterQubits/InstrumentControl.jl/blob/952a9d3c8d2c3293eeff0f289bc20b6647817ef6/src/instruments/AWGs/M320XA/Inspect.jl#L17>
can give different results:

[image: image]
<https://user-images.githubusercontent.com/7145721/35022653-e94eb92a-faeb-11e7-9357-9ec37dff0f17.png>

cc @vtdsferreira <https://github.com/vtdsferreira>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/PainterQubits/InstrumentControl.jl/issues/33>, or mute
the thread

**Comment by ajkeller34** [comment]
Found the issue. Running `keys(awg3.channels)` yields `[4,2,3,1]`, and in my `getindex(ins, Type{T}) where {T<:InstrumentProperty}` function, I iterate over `keys(ins.channels)`.  A simple fix is to just iterate over `sort(collect(keys(ins.channels)))`

**Comment by vtdsferreira** [comment]
Found the issue. Running keys(awg3.channels) yields [4,2,3,1], and in my getindex(ins, Type{T}) where {T<:InstrumentProperty} function, I iterate over keys(ins.channels). A simple fix is to just iterate over sort(collect(keys(ins.channels)))
